### ISSUE TITLE
queueに曲があるにも関わらず再生終了後に次の曲が再生されない場合がある。

### ISSUE THREAD

**Issue by sakkuntyo** [sakkuntyo/discord-sktrythmjs#3]
ログがなんもでない。。。。。。。。。。。。

**Comment by sakkuntyo** [comment]
以下コードを追加して再現時に出たログ

      .on("error", console.error)
      .on("debug", console.log);

MinigetError: input stream: Status code: 403
    at ClientRequest.<anonymous> (/home/noma/discord-sktrythmjs/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9) {
  statusCode: 403

GitHub の API 制限に抵触？

https://github.com/fent/node-ytdl-core/issues/798

**Comment by sakkuntyo** [comment]
8fe7a8e90879eeb669aa9759e397192774f16163 で対応、エラーは出るものの、継続再生される様になりました。
